import { columns, Payment } from './columns'
import { DataTable } from './data-table'

const getData = async (): Promise<Payment[]> => {
  return [
    {
      id: '728ed521',
      amount: 134,
      status: 'pending',
      fullName: 'Richard Ren',
      userId: '52',
      email: 'richardren@gmail.com',
    },
    {
      id: '728ed522',
      amount: 124,
      status: 'success',
      fullName: 'Jane Ren',
      userId: '81',
      email: 'janeren@gmail.com',
    },
    {
      id: '728ed523',
      amount: 167,
      status: 'success',
      fullName: 'Mike Galloway',
      userId: '23',
      email: 'mikegalloway@gmail.com',
    },
    {
      id: '728ed524',
      amount: 156,
      status: 'failed',
      fullName: 'Minerva Robinson',
      userId: '48',
      email: 'minerbarobinson@gmail.com',
    },
    {
      id: '728ed525',
      amount: 145,
      status: 'success',
      fullName: 'Mable Clayton',
      userId: '90',
      email: 'mableclayton@gmail.com',
    },
    {
      id: '728ed526',
      amount: 189,
      status: 'pending',
      fullName: 'Nathan McDaniel',
      userId: '28',
      email: 'nathanmcdaniel@gmail.com',
    },
    {
      id: '728ed527',
      amount: 178,
      status: 'success',
      fullName: 'Myrtie Lamb',
      userId: '79',
      email: 'myrtielamb@gmail.com',
    },
    {
      id: '728ed528',
      amount: 190,
      status: 'success',
      fullName: 'Leona Bryant',
      userId: '92',
      email: 'leonabryant@gmail.com',
    },
    {
      id: '728ed529',
      amount: 134,
      status: 'failed',
      fullName: 'Aaron Willis',
      userId: '53',
      email: 'aaronwillis@gmail.com',
    },
    {
      id: '728ed52a',
      amount: 543,
      status: 'success',
      fullName: 'Joel Keller',
      userId: '13',
      email: 'joelkeller@gmail.com',
    },
    {
      id: '728ed52b',
      amount: 234,
      status: 'pending',
      fullName: 'Daniel Ellis',
      userId: '69',
      email: 'danielellis@gmail.com',
    },
    {
      id: '728ed52c',
      amount: 345,
      status: 'success',
      fullName: 'Gordon Kennedy',
      userId: '29',
      email: 'gordonkennedy@gmail.com',
    },
    {
      id: '728ed52d',
      amount: 335,
      status: 'failed',
      fullName: 'Emily Hoffman',
      userId: '94',
      email: 'emilyhoffman@gmail.com',
    },
    {
      id: '728ed52e',
      amount: 664,
      status: 'pending',
      fullName: 'Jeffery Garrett',
      userId: '93',
      email: 'jefferygarrett@gmail.com',
    },
    {
      id: '728ed52f',
      amount: 332,
      status: 'success',
      fullName: 'Ralph Baker',
      userId: '57',
      email: 'ralphbaker@gmail.com',
    },
    {
      id: '728ed52g',
      amount: 413,
      status: 'failed',
      fullName: 'Seth Fields',
      userId: '45',
      email: 'sethfields@gmail.com',
    },
    {
      id: '728ed52h',
      amount: 345,
      status: 'pending',
      fullName: 'Julia Webb',
      userId: '80',
      email: 'juliawebb@gmail.com',
    },
    {
      id: '728ed52i',
      amount: 754,
      status: 'success',
      fullName: 'Gary Banks',
      userId: '50',
      email: 'garybanks@gmail.com',
    },
    {
      id: '728ed52j',
      amount: 643,
      status: 'failed',
      fullName: 'Flora Chambers',
      userId: '82',
      email: 'florachambers@gmail.com',
    },
    {
      id: '728ed52k',
      amount: 543,
      status: 'pending',
      fullName: 'Steve Hanson',
      userId: '13',
      email: 'stevehanson@gmail.com',
    },
    {
      id: '728ed52l',
      amount: 324,
      status: 'success',
      fullName: 'Lola Robinson',
      userId: '54',
      email: 'lolarobinson@gmail.com',
    },
    {
      id: '728ed52m',
      amount: 123,
      status: 'pending',
      fullName: 'Ethel Waters',
      userId: '55',
      email: 'ethelwaters@gmail.com',
    },
    {
      id: '728ed52n',
      amount: 422,
      status: 'failed',
      fullName: 'Grace Edwards',
      userId: '52',
      email: 'graceedwards@gmail.com',
    },
    {
      id: '728ed52o',
      amount: 712,
      status: 'success',
      fullName: 'Sallie Wong',
      userId: '5',
      email: 'salliewong@gmail.com',
    },
    {
      id: '728ed52p',
      amount: 360,
      status: 'success',
      fullName: 'Bryan Gutierrez',
      userId: '80',
      email: 'bryangutierrez@gmail.com',
    },
    {
      id: '728ed52q',
      amount: 454,
      status: 'pending',
      fullName: 'Erik Rice',
      userId: '10',
      email: 'erikrice@gmail.com',
    },
    {
      id: '728ed52r',
      amount: 382,
      status: 'success',
      fullName: 'Jordan Atkins',
      userId: '16',
      email: 'jordanatkins@gmail.com',
    },
    {
      id: '728ed52s',
      amount: 328,
      status: 'failed',
      fullName: 'Bill Brewer',
      userId: '28',
      email: 'billbrewer@gmail.com',
    },
    {
      id: '728ed52t',
      amount: 250,
      status: 'success',
      fullName: 'Edwin Morris',
      userId: '28',
      email: 'edwinmorris@gmail.com',
    },
    {
      id: '728ed52u',
      amount: 658,
      status: 'success',
      fullName: 'Harold Becker',
      userId: '74',
      email: 'haroldbecker@gmail.com',
    },
    {
      id: '728ed52v',
      amount: 691,
      status: 'success',
      fullName: 'Hannah Rodriguez',
      userId: '54',
      email: 'hannahrodriguez@gmail.com',
    },
    {
      id: '728ed52w',
      amount: 969,
      status: 'success',
      fullName: 'Zachary Beck',
      userId: '12',
      email: 'zacharybeck@gmail.com',
    },
    {
      id: '728ed52x',
      amount: 617,
      status: 'failed',
      fullName: 'Frances Potter',
      userId: '9',
      email: 'francespotter@gmail.com',
    },
    {
      id: '728ed52y',
      amount: 173,
      status: 'success',
      fullName: 'Raymond Murray',
      userId: '3',
      email: 'raymondmurray@gmail.com',
    },
    {
      id: '728ed52z',
      amount: 843,
      status: 'success',
      fullName: 'Adam Sherman',
      userId: '58',
      email: 'adamsherman@gmail.com',
    },
    {
      id: '728ed521f',
      amount: 914,
      status: 'pending',
      fullName: 'Anne Cruz',
      userId: '18',
      email: 'annecruz@gmail.com',
    },
  ]
}

const PaymentsPage = async () => {
  const data = await getData()

  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">All Payments</h1>
      </div>
      <DataTable columns={columns} data={data} />
    </div>
  )
}

export default PaymentsPage
